### ISSUE TITLE
Migrate from create-react-app-typescript to Create React App

### ISSUE THREAD

**Issue by adrianmxb** [highcard-dev/ecom-frontend#1]
If we don't plan to eject from the create-react-app environment soon we should consider switching over to Create React App as they introduced Typescript support with v2.1 and [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) isn't maintained anymore.

**Comment by Dijky** [comment]
This project was initialized with the mainline version of create-react-app using the following command (taken directly from my shell history):

    npx create-react-app ecom-frontend --typescript
